/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\learn\\blog\\vuepress-theme-vdoing\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-283c082e",
    path: "/web/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-283c082e").then(next)
    },
  },
  {
    path: "/web/index.html",
    redirect: "/web/"
  },
  {
    path: "/00.目录页/01.前端.html",
    redirect: "/web/"
  },
  {
    name: "v-04f4b11e",
    path: "/star/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04f4b11e").then(next)
    },
  },
  {
    path: "/star/index.html",
    redirect: "/star/"
  },
  {
    path: "/00.目录页/06.收藏.html",
    redirect: "/star/"
  },
  {
    name: "v-30d4261b",
    path: "/more/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-30d4261b").then(next)
    },
  },
  {
    path: "/more/index.html",
    redirect: "/more/"
  },
  {
    path: "/00.目录页/04.更多.html",
    redirect: "/more/"
  },
  {
    name: "v-2aed8fd7",
    path: "/server/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2aed8fd7").then(next)
    },
  },
  {
    path: "/server/index.html",
    redirect: "/server/"
  },
  {
    path: "/00.目录页/02.后端.html",
    redirect: "/server/"
  },
  {
    name: "v-64646687",
    path: "/pages/114158caa9e96df0/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64646687").then(next)
    },
  },
  {
    path: "/pages/114158caa9e96df0/index.html",
    redirect: "/pages/114158caa9e96df0/"
  },
  {
    path: "/01.前端/20.Vue/01.基础/00.MVVM模式.html",
    redirect: "/pages/114158caa9e96df0/"
  },
  {
    name: "v-483159dc",
    path: "/pages/351f72ecd9c41129/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-483159dc").then(next)
    },
  },
  {
    path: "/pages/351f72ecd9c41129/index.html",
    redirect: "/pages/351f72ecd9c41129/"
  },
  {
    path: "/01.前端/20.Vue/01.基础/20.计算属性 vs 方法 vs 侦听属性.html",
    redirect: "/pages/351f72ecd9c41129/"
  },
  {
    name: "v-0b880dec",
    path: "/pages/73e4064340277b05/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0b880dec").then(next)
    },
  },
  {
    path: "/pages/73e4064340277b05/index.html",
    redirect: "/pages/73e4064340277b05/"
  },
  {
    path: "/01.前端/20.Vue/01.基础/30.v-if vs v-show.html",
    redirect: "/pages/73e4064340277b05/"
  },
  {
    name: "v-cd557bd4",
    path: "/pages/176808a1b5f843b8/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cd557bd4").then(next)
    },
  },
  {
    path: "/pages/176808a1b5f843b8/index.html",
    redirect: "/pages/176808a1b5f843b8/"
  },
  {
    path: "/01.前端/20.Vue/01.基础/10.生命周期.html",
    redirect: "/pages/176808a1b5f843b8/"
  },
  {
    name: "v-1ca9aa86",
    path: "/pages/04783a6691cc9d06/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ca9aa86").then(next)
    },
  },
  {
    path: "/pages/04783a6691cc9d06/index.html",
    redirect: "/pages/04783a6691cc9d06/"
  },
  {
    path: "/01.前端/20.Vue/01.基础/35.列表渲染之数组、对象更新检测.html",
    redirect: "/pages/04783a6691cc9d06/"
  },
  {
    name: "v-1c8cd458",
    path: "/note/js/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c8cd458").then(next)
    },
  },
  {
    path: "/note/js/index.html",
    redirect: "/note/js/"
  },
  {
    path: "/01.前端/05.JavaScript.html",
    redirect: "/note/js/"
  },
  {
    name: "v-2a84cbca",
    path: "/pages/07b384c2e6232e07/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a84cbca").then(next)
    },
  },
  {
    path: "/pages/07b384c2e6232e07/index.html",
    redirect: "/pages/07b384c2e6232e07/"
  },
  {
    path: "/01.前端/20.Vue/02.组件/40.父组件给子组件传值.html",
    redirect: "/pages/07b384c2e6232e07/"
  },
  {
    name: "v-900a78e8",
    path: "/pages/83a1ab785e7fd70c/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-900a78e8").then(next)
    },
  },
  {
    path: "/pages/83a1ab785e7fd70c/index.html",
    redirect: "/pages/83a1ab785e7fd70c/"
  },
  {
    path: "/01.前端/20.Vue/02.组件/36.使用组件的细节点.html",
    redirect: "/pages/83a1ab785e7fd70c/"
  },
  {
    name: "v-2fd946f1",
    path: "/pages/0f19a1bcac14fd41/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2fd946f1").then(next)
    },
  },
  {
    path: "/pages/0f19a1bcac14fd41/index.html",
    redirect: "/pages/0f19a1bcac14fd41/"
  },
  {
    path: "/01.前端/20.Vue/02.组件/50.子组件派发事件和值给父组件.html",
    redirect: "/pages/0f19a1bcac14fd41/"
  },
  {
    name: "v-7446bb36",
    path: "/pages/a3080f60f6596eb4/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7446bb36").then(next)
    },
  },
  {
    path: "/pages/a3080f60f6596eb4/index.html",
    redirect: "/pages/a3080f60f6596eb4/"
  },
  {
    path: "/01.前端/20.Vue/02.组件/52.Prop 验证 与 非 Prop 的 Attribute.html",
    redirect: "/pages/a3080f60f6596eb4/"
  },
  {
    name: "v-4fa8022e",
    path: "/pages/d408e64f666f146d/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4fa8022e").then(next)
    },
  },
  {
    path: "/pages/d408e64f666f146d/index.html",
    redirect: "/pages/d408e64f666f146d/"
  },
  {
    path: "/01.前端/20.Vue/02.组件/65.非父子组件传值.html",
    redirect: "/pages/d408e64f666f146d/"
  },
  {
    name: "v-026aecce",
    path: "/pages/9651417d08d1779d/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-026aecce").then(next)
    },
  },
  {
    path: "/pages/9651417d08d1779d/index.html",
    redirect: "/pages/9651417d08d1779d/"
  },
  {
    path: "/01.前端/20.Vue/02.组件/55.自定义事件.html",
    redirect: "/pages/9651417d08d1779d/"
  },
  {
    name: "v-85394184",
    path: "/pages/2e24dab728769e0c/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-85394184").then(next)
    },
  },
  {
    path: "/pages/2e24dab728769e0c/index.html",
    redirect: "/pages/2e24dab728769e0c/"
  },
  {
    path: "/01.前端/20.Vue/02.组件/70.父组件调用子组件方法并传入值.html",
    redirect: "/pages/2e24dab728769e0c/"
  },
  {
    name: "v-18937c2a",
    path: "/pages/e6cec47efa42d7f1/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-18937c2a").then(next)
    },
  },
  {
    path: "/pages/e6cec47efa42d7f1/index.html",
    redirect: "/pages/e6cec47efa42d7f1/"
  },
  {
    path: "/01.前端/20.Vue/02.组件/90.vue父子组件的生命周期顺序.html",
    redirect: "/pages/e6cec47efa42d7f1/"
  },
  {
    name: "v-92d79da4",
    path: "/pages/809f4582d9ca9552/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-92d79da4").then(next)
    },
  },
  {
    path: "/pages/809f4582d9ca9552/index.html",
    redirect: "/pages/809f4582d9ca9552/"
  },
  {
    path: "/01.前端/20.Vue/02.组件/60.兄弟组件传值.html",
    redirect: "/pages/809f4582d9ca9552/"
  },
  {
    name: "v-595dcc32",
    path: "/pages/636ca33122e9a64b/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-595dcc32").then(next)
    },
  },
  {
    path: "/pages/636ca33122e9a64b/index.html",
    redirect: "/pages/636ca33122e9a64b/"
  },
  {
    path: "/01.前端/20.Vue/02.组件/80.动态组件与 v-once 指令.html",
    redirect: "/pages/636ca33122e9a64b/"
  },
  {
    name: "v-7868f62e",
    path: "/pages/184a96b493a97078/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7868f62e").then(next)
    },
  },
  {
    path: "/pages/184a96b493a97078/index.html",
    redirect: "/pages/184a96b493a97078/"
  },
  {
    path: "/01.前端/20.Vue/03.过渡&动画/110.transition过渡&动画.html",
    redirect: "/pages/184a96b493a97078/"
  },
  {
    name: "v-f5e8b996",
    path: "/pages/055ecee9a4325386/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f5e8b996").then(next)
    },
  },
  {
    path: "/pages/055ecee9a4325386/index.html",
    redirect: "/pages/055ecee9a4325386/"
  },
  {
    path: "/01.前端/20.Vue/02.组件/75.插槽slot.html",
    redirect: "/pages/055ecee9a4325386/"
  },
  {
    name: "v-21636ca8",
    path: "/pages/d00311f8174119b2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21636ca8").then(next)
    },
  },
  {
    path: "/pages/d00311f8174119b2/index.html",
    redirect: "/pages/d00311f8174119b2/"
  },
  {
    path: "/01.前端/20.Vue/05.工具/10.Vue CLi v3 创建项目使用记录.html",
    redirect: "/pages/d00311f8174119b2/"
  },
  {
    name: "v-3b40a412",
    path: "/pages/3b0a20e70805fcea/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b40a412").then(next)
    },
  },
  {
    path: "/pages/3b0a20e70805fcea/index.html",
    redirect: "/pages/3b0a20e70805fcea/"
  },
  {
    path: "/01.前端/20.Vue/03.过渡&动画/112.使用animate库.html",
    redirect: "/pages/3b0a20e70805fcea/"
  },
  {
    name: "v-9c43971e",
    path: "/pages/0aa92922ace6bb5e/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9c43971e").then(next)
    },
  },
  {
    path: "/pages/0aa92922ace6bb5e/index.html",
    redirect: "/pages/0aa92922ace6bb5e/"
  },
  {
    path: "/01.前端/20.Vue/03.过渡&动画/120.transition-group列表过渡.html",
    redirect: "/pages/0aa92922ace6bb5e/"
  },
  {
    name: "v-14f5e801",
    path: "/pages/bd36a3c1bc3e0821/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14f5e801").then(next)
    },
  },
  {
    path: "/pages/bd36a3c1bc3e0821/index.html",
    redirect: "/pages/bd36a3c1bc3e0821/"
  },
  {
    path: "/01.前端/20.Vue/04.可复用性&组合/01.Mixin混入.html",
    redirect: "/pages/bd36a3c1bc3e0821/"
  },
  {
    name: "v-f0a8c70c",
    path: "/pages/38ecac9a9b92f037/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f0a8c70c").then(next)
    },
  },
  {
    path: "/pages/38ecac9a9b92f037/index.html",
    redirect: "/pages/38ecac9a9b92f037/"
  },
  {
    path: "/01.前端/20.Vue/06.规模化/140.路由懒加载.html",
    redirect: "/pages/38ecac9a9b92f037/"
  },
  {
    name: "v-2a8f44c4",
    path: "/pages/d9d62d6ab8ff99a6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a8f44c4").then(next)
    },
  },
  {
    path: "/pages/d9d62d6ab8ff99a6/index.html",
    redirect: "/pages/d9d62d6ab8ff99a6/"
  },
  {
    path: "/01.前端/20.Vue/06.规模化/100.vuex操作相关.html",
    redirect: "/pages/d9d62d6ab8ff99a6/"
  },
  {
    name: "v-616ed8b5",
    path: "/pages/30a94dbe96873b33/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-616ed8b5").then(next)
    },
  },
  {
    path: "/pages/30a94dbe96873b33/index.html",
    redirect: "/pages/30a94dbe96873b33/"
  },
  {
    path: "/01.前端/20.Vue/99.其他/90.操作本地缓存.html",
    redirect: "/pages/30a94dbe96873b33/"
  },
  {
    name: "v-4039c83c",
    path: "/pages/b30620/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4039c83c").then(next)
    },
  },
  {
    path: "/pages/b30620/index.html",
    redirect: "/pages/b30620/"
  },
  {
    path: "/01.前端/20.Vue/10.Vuex/01.Vuex.html",
    redirect: "/pages/b30620/"
  },
  {
    name: "v-cfe3011e",
    path: "/pages/fb08e252dfd8fdfd/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cfe3011e").then(next)
    },
  },
  {
    path: "/pages/fb08e252dfd8fdfd/index.html",
    redirect: "/pages/fb08e252dfd8fdfd/"
  },
  {
    path: "/01.前端/20.Vue/99.其他/80.Vue中的防抖函数封装和使用.html",
    redirect: "/pages/fb08e252dfd8fdfd/"
  },
  {
    name: "v-3110c0c5",
    path: "/pages/30c04c/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3110c0c5").then(next)
    },
  },
  {
    path: "/pages/30c04c/index.html",
    redirect: "/pages/30c04c/"
  },
  {
    path: "/02.后端/05.spring/01.IOC.html",
    redirect: "/pages/30c04c/"
  },
  {
    name: "v-24e94234",
    path: "/pages/51afd6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-24e94234").then(next)
    },
  },
  {
    path: "/pages/51afd6/index.html",
    redirect: "/pages/51afd6/"
  },
  {
    path: "/01.前端/35.TypeScript.html",
    redirect: "/pages/51afd6/"
  },
  {
    name: "v-61227f60",
    path: "/pages/8292d8/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-61227f60").then(next)
    },
  },
  {
    path: "/pages/8292d8/index.html",
    redirect: "/pages/8292d8/"
  },
  {
    path: "/02.后端/66.Git学习笔记/10.手册/00.常用Git命令清单.html",
    redirect: "/pages/8292d8/"
  },
  {
    name: "v-474c79bf",
    path: "/pages/635088/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-474c79bf").then(next)
    },
  },
  {
    path: "/pages/635088/index.html",
    redirect: "/pages/635088/"
  },
  {
    path: "/02.后端/66.Git学习笔记/10.手册/10.Git基础与命令.html",
    redirect: "/pages/635088/"
  },
  {
    name: "v-e59b303c",
    path: "/pages/baaa02/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e59b303c").then(next)
    },
  },
  {
    path: "/pages/baaa02/index.html",
    redirect: "/pages/baaa02/"
  },
  {
    path: "/04.更多/10.实用技巧/01.2分钟规则.html",
    redirect: "/pages/baaa02/"
  },
  {
    name: "v-22c17f52",
    path: "/pages/d5b6a0/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-22c17f52").then(next)
    },
  },
  {
    path: "/pages/d5b6a0/index.html",
    redirect: "/pages/d5b6a0/"
  },
  {
    path: "/06.收藏夹/04.后端网站资源.html",
    redirect: "/pages/d5b6a0/"
  },
  {
    name: "v-8ef75fa8",
    path: "/pages/2d615df9a36a98ed/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8ef75fa8").then(next)
    },
  },
  {
    path: "/pages/2d615df9a36a98ed/index.html",
    redirect: "/pages/2d615df9a36a98ed/"
  },
  {
    path: "/04.更多/05.心情杂货/01.一个完美主义者的自我救赎.html",
    redirect: "/pages/2d615df9a36a98ed/"
  },
  {
    name: "v-038dde65",
    path: "/pages/dcebaf/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-038dde65").then(next)
    },
  },
  {
    path: "/pages/dcebaf/index.html",
    redirect: "/pages/dcebaf/"
  },
  {
    path: "/04.更多/10.实用技巧/10.一行代码“黑”掉任意网站.html",
    redirect: "/pages/dcebaf/"
  },
  {
    name: "v-30389460",
    path: "/pages/beb6c0bd8a66cea6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-30389460").then(next)
    },
  },
  {
    path: "/pages/beb6c0bd8a66cea6/index.html",
    redirect: "/pages/beb6c0bd8a66cea6/"
  },
  {
    path: "/06.收藏夹/01.前端网站资源.html",
    redirect: "/pages/beb6c0bd8a66cea6/"
  },
  {
    name: "v-c6aaadf2",
    path: "/archives/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c6aaadf2").then(next)
    },
  },
  {
    path: "/archives/index.html",
    redirect: "/archives/"
  },
  {
    path: "/@pages/archivesPage.html",
    redirect: "/archives/"
  },
  {
    name: "v-250e3e9c",
    path: "/pages/3bd45d/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-250e3e9c").then(next)
    },
  },
  {
    path: "/pages/3bd45d/index.html",
    redirect: "/pages/3bd45d/"
  },
  {
    path: "/06.收藏夹/06.学习.html",
    redirect: "/pages/3bd45d/"
  },
  {
    name: "v-432ff40c",
    path: "/pages/f2e63f/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-432ff40c").then(next)
    },
  },
  {
    path: "/pages/f2e63f/index.html",
    redirect: "/pages/f2e63f/"
  },
  {
    path: "/_posts/随笔/你知道的越多，不知道的也就越多.html",
    redirect: "/pages/f2e63f/"
  },
  {
    name: "v-3b7eb087",
    path: "/tags/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b7eb087").then(next)
    },
  },
  {
    path: "/tags/index.html",
    redirect: "/tags/"
  },
  {
    path: "/@pages/tagsPage.html",
    redirect: "/tags/"
  },
  {
    name: "v-c700709a",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c700709a").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-1bdfd932",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1bdfd932").then(next)
    },
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    path: "/@pages/categoriesPage.html",
    redirect: "/categories/"
  },
  {
    name: "v-1d737f0c",
    path: "/pages/cd8bde/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1d737f0c").then(next)
    },
  },
  {
    path: "/pages/cd8bde/index.html",
    redirect: "/pages/cd8bde/"
  },
  {
    path: "/_posts/随笔/拥抱生活，拥抱快乐.html",
    redirect: "/pages/cd8bde/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]